services:
  - type: web
    name: oldbook-server
    env: node
    rootDir: Server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: oldbook-client
    env: static
    rootDir: Client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: VITE_API_BASE_URL
        sync: false
