services:
  - type: web
    name: oldbook-server
    env: node
    buildCommand: cd Server && npm install
    startCommand: cd Server && npm start
    autoDeploy: true

  - type: web
    name: oldbook-client
    env: static
    buildCommand: cd Client && npm install && npm run build
    staticPublishPath: Client/dist
    pullRequestPreviewsEnabled: true
